version: "3.8"

services:
  database:
    image: postgres:15.3-alpine3.18
    container_name: postgres_kursovaya
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpass123
      - POSTGRES_DB=kursovaya
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data/

volumes:
  postgresdata:
